# Change baseurl before deploy
baseurl = "https://dstipscafe.github.io/blogs"
languageCode = "zh-tw"
paginate = 5
title = "資料科學咖啡館&小秘訣分享 | Data Science Cafe & Tips"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-tw"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "https-dstipscafe-github-io"

