# Rename this file to languages.toml to enable multilingual support
[zh-tw]
languageName = "Chinese (Traditional) (Taiwan)"
languagedirection = "ltr"
title = "測試"
weight = 1
contentDir = 'content/zh-tw'
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1
