# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/dstipscafe"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Instagram"
url = "https://www.instagram.com/ds_cafe_and_tips/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "Portaly"
name = "Portaly"
url = "https://portaly.cc/ds_tips_cafe"

[social.params]
icon = "external-link"
